# Generated by Django 4.0.2 on 2022-02-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_statusmodel_statuses_alter_typemodel_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='statuses',
            field=models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В Процессе'), ('Done', 'Сделано')], default='New', max_length=11, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='typemodel',
            name='types',
            field=models.CharField(choices=[('Task', 'Задача'), ('Bug', 'Ошибка'), ('Enhancement', 'Улучшение')], default='Task', max_length=11, verbose_name='Тип'),
        ),
    ]
