# Generated by Django 4.0.2 on 2022-02-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_issue_type_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='webapp.statusmodel', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(related_name='issues', to='webapp.TypeModel'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='statuses',
            field=models.CharField(max_length=11, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='typemodel',
            name='types',
            field=models.CharField(max_length=11, verbose_name='Тип'),
        ),
    ]
