# Generated by Django 4.0.2 on 2022-02-15 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='webapp.issue', verbose_name='Проект'),
        ),
    ]
