# Generated by Django 4.0.2 on 2022-02-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_project_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(verbose_name='Дата Создания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='issue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='webapp.issue', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateField(verbose_name='Дата Редактирования'),
        ),
    ]
